### ISSUE TITLE
mp4 scrollbar

### ISSUE THREAD

**Issue by vivonslasieste** [satishsampath/wink-issues#7]
I don't know if this point can be improved :
Could the scrollbar at the bottom of the mp4 have a forward/backward button?
Or at least could we move backwards when clicking on it ?
![Annotation 2020-09-02 03](https://user-images.githubusercontent.com/70328086/91944084-d2753880-ecfd-11ea-9b5a-f885bfff0f11.png)

Thank you for all your work

**Comment by satishsampath** [comment]
I decided not to support free movement across the video, because content creators such as yourself would want the tutorial to be viewed in a certain way.. that's why we have the various types of buttons, pause, resume, callouts, etc. For this release, I'm going to keep it that way. If there is enough support/requests/reason for free movement across the video, I can add it in a future release.
